### PR TITLE
tool_destination.yml - add some xcms tools

### PR DESCRIPTION
**Pull request by lecorguille**
I'm using this file to set our job_conf :)
So since, I need to update mine, I'm wondering if those settings are welcome for you!?

### CODE REVIEW

**Comment by bgruening** [comment]
I'm in favor of this! I will let @gmauro decide.

**Comment by lecorguille** [comment]
Oups, thanks @gmauro

**Comment by gmauro** [comment]
it's a little bizarre and I hope is clear we can change everything here without notice if needed for usegalaxy.eu

**Comment by lecorguille** [comment]
Copy that!
I really love this file. We didn't have implement the sorting-hat in usegalaxy.fr yet but I still run this file with a homemade script to convert it in a classic job_conf.

**Pull request merged**
